### PR TITLE
ported to Ryven 3.1 dev and minor refactoring

### PR DESCRIPTION
**Pull request by leon-thomm**
PR to port this to Ryven 3.1 which is not released yet, so **do not merge yet**. Ryven 3.1 will be a major upgrade for this project too, see also my comment [here](https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/discussions/2#discussioncomment-1711112).

### CODE REVIEW

**Comment by leon-thomm** [comment]
integrated 3d3eede2c4a17c41f56911f585177f19bdd17eee

**Comment by Tanneguydv** [comment]
When ready to pull, could you integrate the last commit about the `Section_Node` change?

[https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/commit/ab01677ab676c18ffa8528319fa568831756946c](https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/commit/ab01677ab676c18ffa8528319fa568831756946c)

**Comment by leon-thomm** [comment]
alright, I added the remaining parts, I think you can merge

**Comment by Tanneguydv** [comment]
your 'added versions' commit consists in adding `verion = 'v0.1'` to each node, did you mean `version = 'v0.1'` ?

**Comment by leon-thomm** [comment]
oh my goodness, you're right, sorry about that, just fixed it

**Pull request merged**
